# Generated by Django 3.2 on 2021-05-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_products_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('Category', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=100)),
                ('Price', models.CharField(default='', max_length=100)),
                ('Image', models.ImageField(upload_to='products')),
                ('availableqty', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.add_products_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.user_tb')),
            ],
        ),
    ]
